_target_: eqx_nerf.SpatioTempNerF
basis_net:
  _target_: eqx_nerf.RFFNet
  in_size: 3
  out_size: 1
  width_size: 256
  num_features: 128
  depth: 5
  ard: False
  method: "rbf"
  key:
    _target_: jax.random.PRNGKey
    seed: 123
