_target_: eqx_nerf.SpatioTempNerF
basis_net:
  _target_: equinox.nn.MLP
  in_size: 3
  out_size: 1
  width_size: 256
  depth: 5
  activation:
    _target_: eqx_nerf.ReLU
  final_activation:
    _target_: equinox.nn.Identity
  key:
    _target_: jax.random.PRNGKey
    seed: 123
