_target_: jejeqx._src.transforms.pipelines.make_pipeline

steps_config:
  - cartesian3d:
      _target_: jejeqx._src.transforms.dataframe.spatial.Spherical2Cartesian
      radius: 1.0
      units: "degrees"

  - spatialminmax:
      _target_: jejeqx._src.transforms.dataframe.scaling.MinMaxDF
      columns: ["x", "y", "z"]
      min_val: -1
      max_val: 1
