natl60_dc20a:
    _target_: jejeqx._src.datamodules.coords_v2.AlongTrackDM
    paths: "/gpfswork/rech/cli/uvo53rl/projects/jejeqx/data/natl60/NATL60-CJM165_GULFSTREAM_ssh_y2013.1y.nc"
    batch_size: 10_000
    shuffle: True
    train_size: 0.80
    subset_size: 0.40
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh"]
    evaluation: False
    resample: "1D"
    decode_times: False
    spatial_units: "meters"
    time_unit: "seconds"
    time_freq: 1
    t0: "2013-01-01"
    select:
        time: {_target_: builtins.slice, _args_: ["2013-01-01", "2013-01-01"]}


natl60_dc20a_scaled:
    _target_: jejeqx._src.datamodules.coords_v2.AlongTrackDM
    paths: "/gpfswork/rech/cli/uvo53rl/projects/jejeqx/data/natl60/NATL60-CJM165_GULFSTREAM_ssh_y2013.1y.nc"
    batch_size: 10_000
    shuffle: True
    train_size: 0.80
    subset_size: 0.40
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["ssh"]
    evaluation: False
    resample: "1D"
    decode_times: False
    spatial_units: "meters"
    time_unit: "seconds"
    time_freq: 1
    t0: "2013-01-01"
    select:
        time: {_target_: builtins.slice, _args_: ["2013-01-01", "2013-01-01"]}

    temporal_transform: ${temporal_transforms}
    spatial_transform: ${spatial_transforms}

spatial_transforms:
    _target_: jejeqx._src.transforms.pipelines.make_pipeline
    _recursive_: False
    steps_config:
        - spatialminmax:
            _target_: jejeqx._src.transforms.dataframe.scaling.MinMaxDF
            columns: ["lat", "lon"]
            min_val: -1
            max_val: 1

temporal_transforms:
    _target_: jejeqx._src.transforms.pipelines.make_pipeline
    _recursive_: False
    steps_config:
        - timeminmax:
            _target_: jejeqx._src.transforms.dataframe.scaling.MinMaxDF
            columns: ["time"]
            min_val: -1
            max_val: 1


natl60_dc20a_eval:
    _target_: "jejeqx._src.datamodules.coords.EvalCoordDM"
    paths: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/test/dc_ref/NATL60-CJM165_GULFSTREAM*"
    batch_size: 10_000
    shuffle: False
    train_size: 0.80
    decode_times: True
    evaluation: True
    spatial_coords: ["lat", "lon"]
    temporal_coords: ["time"]
    variables: ["sossheig"]
    coarsen:
        lon: 2
        lat: 2
    resample: "1D"
    select:
        time: {_target_: builtins.slice, _args_: ["2012-10-01", "2012-12-02"]}
