domain:
  lat: {_target_: "builtins.slice", _args_: [32., 44.]}
  lon: {_target_: "builtins.slice", _args_: [-66., -54.]}
  time: {_target_: "builtins.slice", _args_: ["2012-10-22", "2012-12-02"]}

registry: ../sla-data-registry
geoval: "oceanbench._src.geoprocessing.validation"

select:
    _target_: "xarray.Dataset.sel"
    _partial_: True
    indexers: "${domain}"


# DUACS
DUACS_NADIR:
    name: "duacs"
    experiment: "nadir4"
    variable: "gssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/DUACS/2020a_SSH_mapping_NATL60_DUACS_en_j1_tpn_g2.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            - {_target_: "xarray.Dataset.rename", name_dict: {"gssh": "ssh"}, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "jejeqx._src.transforms.spatial.validate_lon", _partial_: True}
            - {_target_: "jejeqx._src.transforms.spatial.validate_lat", _partial_: True}
            - {_target_: "jejeqx._src.transforms.temporal.validate_time", _partial_: True}
            # RESCALE TIME
            - {_target_: "jejeqx._src.transforms.temporal.decode_cf_time", units: "seconds since 2012-10-01", _partial_: true}
            - {_target_: "jejeqx._src.transforms.xarray.spatial.transform_360_to_180", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}

# MIOST - nadir4
MIOST_NADIR:
    name: "miost"
    experiment: "nadir4"
    variable: "gssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/MIOST/2020a_SSH_mapping_NATL60_MIOST_en_j1_tpn_g2.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            - {_target_: "xarray.Dataset.rename", name_dict: {"gssh": "ssh"}, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "jejeqx._src.transforms.spatial.validate_lon", _partial_: True}
            - {_target_: "jejeqx._src.transforms.spatial.validate_lat", _partial_: True}
            - {_target_: "jejeqx._src.transforms.temporal.validate_time", _partial_: True}
            # RESCALE TIME
            - {_target_: "jejeqx._src.transforms.temporal.decode_cf_time", units: "seconds since 2012-10-01", _partial_: true}
            - {_target_: "jejeqx._src.transforms.xarray.spatial.transform_360_to_180", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}

# NERF - SIREN - nadir4
NERF_SIREN_NADIR:
    name: "nerf_siren"
    experiment: "nadir4"
    variable: "ssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/NerF/nerf_siren_nadir_dc20a.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "jejeqx._src.transforms.spatial.validate_lon", _partial_: True}
            - {_target_: "jejeqx._src.transforms.spatial.validate_lat", _partial_: True}
            - {_target_: "jejeqx._src.transforms.temporal.validate_time", _partial_: True}
            # RESCALE TIME
            - {_target_: "jejeqx._src.transforms.temporal.decode_cf_time", units: "seconds since 2012-10-01", _partial_: true}
            - {_target_: "jejeqx._src.transforms.xarray.spatial.transform_360_to_180", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}

# NERF - FFN - nadir4
NERF_FFN_NADIR:
    name: "nerf_ffn"
    experiment: "nadir4"
    variable: "ssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/NerF/nerf_ffn_nadir_dc20a.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "jejeqx._src.transforms.spatial.validate_lon", _partial_: True}
            - {_target_: "jejeqx._src.transforms.spatial.validate_lat", _partial_: True}
            - {_target_: "jejeqx._src.transforms.temporal.validate_time", _partial_: True}
            # RESCALE TIME
            - {_target_: "jejeqx._src.transforms.temporal.decode_cf_time", units: "seconds since 2012-10-01", _partial_: true}
            - {_target_: "jejeqx._src.transforms.xarray.spatial.transform_360_to_180", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}

# NERF - MLP - nadir4
NERF_MLP_NADIR:
    name: "nerf_mlp"
    experiment: "nadir4"
    variable: "ssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/NerF/nerf_mlp_nadir_dc20a.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "jejeqx._src.transforms.spatial.validate_lon", _partial_: True}
            - {_target_: "jejeqx._src.transforms.spatial.validate_lat", _partial_: True}
            - {_target_: "jejeqx._src.transforms.temporal.validate_time", _partial_: True}
            # RESCALE TIME
            - {_target_: "jejeqx._src.transforms.temporal.decode_cf_time", units: "seconds since 2012-10-01", _partial_: true}
            - {_target_: "jejeqx._src.transforms.xarray.spatial.transform_360_to_180", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}
